In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.288585          -0.020294          -0.132905         -0.995279   
1           0.278419          -0.016411          -0.123520         -0.998245   
2           0.279653          -0.019467          -0.113462         -0.995380   
3           0.279174          -0.026201          -0.123283         -0.996091   
4           0.276629          -0.016570          -0.115362         -0.998139   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  tBodyAcc-mad()-Y  \
0         -0.983111         -0.913526         -0.995112         -0.983185   
1         -0.975300         -0.960322         -0.998807         -0.974914   
2         -0.967187         -0.978944         -0.996520         -0.963668   
3         -0.983403         -0.990675         -0.997099         -0.982750   
4         -0.980817         -0.990482         -0.998321         -0.979672   

   tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  fBodyBodyGyroJerkMag-kurtosis()  \
0         -0.923527         -0.934724  ...                        -0.710304   
1         -0.957686         -0.943068  ...                        -0.861499   
2         -0.977469         -0.938692  ...                        -0.760104   
3         -0.989302         -0.938692  ...                        -0.482845   
4         -0.990441         -0.942469  ...                        -0.699205   

   angle(tBodyAccMean,gravity)  angle(tBodyAccJerkMean),gravityMean)  \
0                    -0.112754                              0.030400   
1                     0.053477                             -0.007435   
2                    -0.118559                              0.177899   
3                    -0.036788                             -0.012892   
4                     0.123320                              0.122542   

   angle(tBodyGyroMean,gravityMean)  angle(tBodyGyroJerkMean,gravityMean)  \
0                         -0.464761                             -0.018446   
1                         -0.732626                              0.703511   
2                          0.100699                              0.808529   
3                          0.640011                             -0.485366   
4                          0.693578                             -0.615971   

   angle(X,gravityMean)  angle(Y,gravityMean)  angle(Z,gravityMean)  subject  \
0             -0.841247              0.179941             -0.058627        1   
1             -0.844788              0.180289             -0.054317        1   
2             -0.848933              0.180637             -0.049118        1   
3             -0.848649              0.181935             -0.047663        1   
4             -0.847865              0.185151             -0.043892        1   

   Activity  
0  STANDING  
1  STANDING  
2  STANDING  
3  STANDING  
4  STANDING  

[5 rows x 563 columns]

In [4]:
X = df.drop(['subject', 'Activity'], axis=1)
X

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
0              0.288585          -0.020294          -0.132905   
1              0.278419          -0.016411          -0.123520   
2              0.279653          -0.019467          -0.113462   
3              0.279174          -0.026201          -0.123283   
4              0.276629          -0.016570          -0.115362   
...                 ...                ...                ...   
7347           0.299665          -0.057193          -0.181233   
7348           0.273853          -0.007749          -0.147468   
7349           0.273387          -0.017011          -0.045022   
7350           0.289654          -0.018843          -0.158281   
7351           0.351503          -0.012423          -0.203867   

      tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
0            -0.995279         -0.983111         -0.913526         -0.995112   
1            -0.998245         -0.975300         -0.960322         -0.998807   
2            -0.995380         -0.967187         -0.978944         -0.996520   
3            -0.996091         -0.983403         -0.990675         -0.997099   
4            -0.998139         -0.980817         -0.990482         -0.998321   
...                ...               ...               ...               ...   
7347         -0.195387          0.039905          0.077078         -0.282301   
7348         -0.235309          0.004816          0.059280         -0.322552   
7349         -0.218218         -0.103822          0.274533         -0.304515   
7350         -0.219139         -0.111412          0.268893         -0.310487   
7351         -0.269270         -0.087212          0.177404         -0.377404   

      tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  \
0            -0.983185         -0.923527         -0.934724  ...   
1            -0.974914         -0.957686         -0.943068  ...   
2            -0.963668         -0.977469         -0.938692  ...   
3            -0.982750         -0.989302         -0.938692  ...   
4            -0.979672         -0.990441         -0.942469  ...   
...                ...               ...               ...  ...   
7347          0.043616          0.060410          0.210795  ...   
7348         -0.029456          0.080585          0.117440  ...   
7349         -0.098913          0.332584          0.043999  ...   
7350         -0.068200          0.319473          0.101702  ...   
7351         -0.038678          0.229430          0.269013  ...   

      fBodyBodyGyroJerkMag-meanFreq()  fBodyBodyGyroJerkMag-skewness()  \
0                           -0.074323                        -0.298676   
1                            0.158075                        -0.595051   
2                            0.414503                        -0.390748   
3                            0.404573                        -0.117290   
4                            0.087753                        -0.351471   
...                               ...                              ...   
7347                        -0.070157                        -0.588433   
7348                         0.165259                        -0.390738   
7349                         0.195034                         0.025145   
7350                         0.013865                         0.063907   
7351                        -0.058402                        -0.387052   

      fBodyBodyGyroJerkMag-kurtosis()  angle(tBodyAccMean,gravity)  \
0                           -0.710304                    -0.112754   
1                           -0.861499                     0.053477   
2                           -0.760104                    -0.118559   
3                           -0.482845                    -0.036788   
4                           -0.699205                     0.123320   
...                               ...                          ...   
7347                        -0.880324                    -0.190437   
7348      

In [81]:
y = df[['Activity']]
y

Activity
0             STANDING
1             STANDING
2             STANDING
3             STANDING
4             STANDING
...                ...
7347  WALKING_UPSTAIRS
7348  WALKING_UPSTAIRS
7349  WALKING_UPSTAIRS
7350  WALKING_UPSTAIRS
7351  WALKING_UPSTAIRS

[7352 rows x 1 columns]

In [86]:
df['Activity'].value_counts()

LAYING                1407
STANDING              1374
SITTING               1286
WALKING               1226
WALKING_UPSTAIRS      1073
WALKING_DOWNSTAIRS     986
Name: Activity, dtype: int64

# 범주형 특성

In [16]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoder.fit(y)
y_encoded = encoder.transform(y)

C:\Users\yeonju\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [17]:
y = y_encoded
y

array([2, 2, 2, ..., 5, 5, 5])

# 로지스틱 회귀

In [18]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(solver="liblinear",random_state=42)

In [107]:
log_reg.fit(X, y)

C:\Users\yeonju\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


LogisticRegression(random_state=42, solver='liblinear')

In [108]:
y_pred = cross_val_predict(log_reg, X, y, cv=10)
conf_mx = confusion_matrix(y, y_pred)
conf_mx

C:\Users\yeonju\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\yeonju\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\yeonju\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\yeonju\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return 

array([[1405,    0,    0,    0,    2,    0],
       [   8, 1205,   73,    0,    0,    0],
       [   0,   84, 1290,    0,    0,    0],
       [   0,    0,    0, 1155,   11,   60],
       [   0,    0,    0,    9,  935,   42],
       [   0,   16,    0,   41,   35,  981]], dtype=int64)

In [103]:
new = pd.DataFrame({'labels': y_pred})

In [104]:
new

labels
0          2
1          2
2          2
3          2
4          2
...      ...
7347       5
7348       5
7349       5
7350       5
7351       5

[7352 rows x 1 columns]

In [106]:
new['labels'].value_counts()

0    1413
2    1363
1    1305
3    1205
5    1083
4     983
Name: labels, dtype: int64

# Decision Tree

In [59]:
from sklearn.tree import DecisionTreeClassifier

In [62]:
tree_clf = DecisionTreeClassifier(max_depth=2, random_state=42)
tree_clf.fit(X, y)

DecisionTreeClassifier(max_depth=2, random_state=42)

In [65]:
from sklearn.model_selection import cross_val_score

tree_score = cross_val_score(tree_clf, X, y, cv=10, scoring="accuracy")

In [67]:
tree_score.mean()

0.5446132800946465

# SVC

In [68]:
from sklearn.svm import SVC

svm_clf = SVC(kernel="linear")
svm_clf.fit(X, y)

SVC(kernel='linear')

In [70]:
svm_score = cross_val_score(svm_clf, X, y, cv=10, scoring="accuracy")
svm_score

array([0.97690217, 0.8736413 , 0.96734694, 0.8585034 , 0.96190476,
       0.96190476, 0.98503401, 0.97278912, 0.98367347, 0.98095238])

In [71]:
svm_score.mean() 

0.9522652321798285


# 에러 분석

In [73]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix

y_pred = cross_val_predict(svm_clf, X, y, cv=10)
conf_mx = confusion_matrix(y, y_pred)

In [74]:
conf_mx

array([[1407,    0,    0,    0,    0,    0],
       [   3, 1215,   67,    0,    0,    1],
       [   0,   74, 1300,    0,    0,    0],
       [   0,    0,    0, 1156,   10,   60],
       [   0,    0,    0,   18,  934,   34],
       [   0,    0,    0,   32,   52,  989]], dtype=int64)